### ISSUE TITLE
新手：初始化登录提示 您还没有添加角色 ，请问如何添加？

### ISSUE THREAD

**Issue by danxinzhicheng** [HyperGenm/old-springboot-vue#2]

**Comment by HyperGenm** [comment]
自己开发的话使用账号:superadmin,密码:111111       演示环境下superadmin禁用了  
添加角色
方法一：改数据库   系统用户表sys_user中账号对应的`role_id`字段就是角色表sys_role中的id
方法二：登入系统后，系统管理->用户管理->操作按钮中的角色按钮
目前doc/template.sql文件中的262行admin对应的角色已经更改了
